import type { Product } from "./types"

export const categories = [
  { id: "rings", name: "Rings", image: "/elegant-gold-ring.jpg" },
  { id: "necklaces", name: "Necklaces", image: "/luxury-necklace-pearls.jpg" },
  { id: "bracelets", name: "Bracelets", image: "/sparkling-diamond-bracelet.png" },
  { id: "earrings", name: "Earrings", image: "/elegant-diamond-earrings.jpg" },
]

export const products: Product[] = [
  {
    id: "1",
    name: "Classic Gold Band Ring",
    description:
      "Timeless 18k gold ring with elegant finish. This exquisite piece features a smooth, polished surface that catches light beautifully. Perfect for everyday wear or special occasions, crafted with premium materials and exceptional attention to detail.",
    price: 2500,
    image: "/classic-gold-band-ring.jpg",
    images: ["/classic-gold-band-ring.jpg", "/elegant-gold-ring.jpg"],
    category: "rings",
    subcategory: "gold",
    type: "wedding",
    inStock: true,
    bestSeller: true,
    productCode: "RG-001-YG",
    designNumber: "D-8847",
    metalClarity: "18K Gold",
    shape: "Band",
    size: "6, 7, 8, 9, 10",
    purityKarat: "18K",
    grossWeightGram: 4.5,
    netWeight: 4.2,
    color: "Yellow Gold",
    tags: ["wedding", "classic", "gold"],
    metalValue: 2000,
    stoneValue: 0,
  },
  {
    id: "2",
    name: "Diamond Solitaire Ring",
    description:
      "Exquisite 1-carat diamond in white gold setting. This stunning engagement ring features a VS1 clarity diamond with ideal cut, set in 18k white gold. A timeless symbol of elegance and sophistication.",
    price: 8500,
    image: "/diamond-solitaire-engagement-ring.jpg",
    images: ["/diamond-solitaire-engagement-ring.jpg", "/elegant-diamond-earrings.jpg"],
    category: "rings",
    subcategory: "diamond",
    type: "engagement",
    inStock: true,
    bestSeller: true,
    productCode: "RG-002-WG",
    designNumber: "D-9201",
    metalClarity: "18K White Gold",
    shape: "Round Brilliant",
    size: "5, 6, 7, 8, 9",
    purityKarat: "18K",
    grossWeightGram: 5.2,
    netWeight: 4.8,
    color: "White Gold",
    tags: ["engagement", "diamond", "solitaire"],
    metalValue: 1500,
    stoneValue: 6500,
  },
  {
    id: "3",
    name: "Pearl Pendant Necklace",
    description:
      "Elegant freshwater pearl on gold chain. This sophisticated necklace features a lustrous white pearl suspended from an 18k yellow gold chain. The pearl's natural beauty is complemented by the warm glow of the gold.",
    price: 1800,
    image: "/pearl-pendant-necklace-luxury.jpg",
    images: ["/pearl-pendant-necklace-luxury.jpg", "/luxury-necklace-pearls.jpg"],
    category: "necklaces",
    subcategory: "pearl",
    type: "pendant",
    inStock: true,
    bestSeller: true,
    productCode: "NK-003-YG",
    designNumber: "D-7634",
    metalClarity: "18K Yellow Gold",
    shape: "Round Pearl",
    size: "18 inches",
    purityKarat: "18K",
    grossWeightGram: 3.8,
    netWeight: 3.5,
    color: "White Pearl",
    tags: ["pearl", "pendant", "elegant"],
    metalValue: 1200,
    stoneValue: 500,
  },
  {
    id: "4",
    name: "Rose Gold Tennis Bracelet",
    description:
      "7.5 inches of shimmering rose gold brilliance. This classic tennis bracelet features a continuous line of diamonds set in rose gold, creating a stunning sparkle that complements any outfit.",
    price: 3200,
    image: "/rose-gold-tennis-bracelet.jpg",
    images: ["/rose-gold-tennis-bracelet.jpg", "/sparkling-diamond-bracelet.png"],
    category: "bracelets",
    subcategory: "gold",
    type: "tennis",
    inStock: true,
    productCode: "BR-004-RG",
    designNumber: "D-5821",
    metalClarity: "14K Rose Gold",
    shape: "Linear",
    size: "7.5 inches",
    purityKarat: "14K",
    grossWeightGram: 6.2,
    netWeight: 5.8,
    color: "Rose Gold",
    tags: ["tennis", "diamonds", "rose gold"],
    metalValue: 1800,
    stoneValue: 1200,
  },
  {
    id: "5",
    name: "Diamond Stud Earrings",
    description:
      "0.5-carat total weight diamond studs. These timeless diamond stud earrings feature perfectly matched diamonds in a classic four-prong setting. Ideal for daily wear and special occasions.",
    price: 2200,
    image: "/diamond-stud-earrings-luxury.jpg",
    images: ["/diamond-stud-earrings-luxury.jpg"],
    category: "earrings",
    subcategory: "diamond",
    type: "stud",
    inStock: true,
    bestSeller: true,
    productCode: "ER-005-WG",
    designNumber: "D-4529",
    metalClarity: "18K White Gold",
    shape: "Round Brilliant",
    size: "Standard",
    purityKarat: "18K",
    grossWeightGram: 2.1,
    netWeight: 1.9,
    color: "White Gold",
    tags: ["studs", "diamonds", "classic"],
    metalValue: 800,
    stoneValue: 1300,
  },
  {
    id: "6",
    name: "Emerald Cut Engagement Ring",
    description:
      "Stunning 2-carat emerald cut diamond. This modern engagement ring features a magnificent 2-carat emerald cut diamond with excellent clarity, set in 18k white gold with tapered baguette side stones.",
    price: 15000,
    image: "/emerald-cut-diamond-ring.jpg",
    images: ["/emerald-cut-diamond-ring.jpg"],
    category: "rings",
    subcategory: "diamond",
    type: "engagement",
    inStock: true,
    bestSeller: true,
    productCode: "RG-006-WG",
    designNumber: "D-2847",
    metalClarity: "18K White Gold",
    shape: "Emerald Cut",
    size: "5, 6, 7, 8",
    purityKarat: "18K",
    grossWeightGram: 6.5,
    netWeight: 6.0,
    color: "White Gold",
    tags: ["engagement", "emerald cut", "luxury"],
    metalValue: 2000,
    stoneValue: 12500,
  },
  {
    id: "7",
    name: "Gold Chain Necklace",
    description:
      "Delicate 18k yellow gold chain, 18 inches. This versatile chain is perfect on its own or paired with a pendant. The fine links create a delicate appearance while maintaining durability.",
    price: 1200,
    image: "/gold-chain-necklace.jpg",
    images: ["/gold-chain-necklace.jpg"],
    category: "necklaces",
    subcategory: "gold",
    type: "chain",
    inStock: true,
    productCode: "NK-007-YG",
    designNumber: "D-1923",
    metalClarity: "18K Yellow Gold",
    shape: "Cable Link",
    size: "18 inches",
    purityKarat: "18K",
    grossWeightGram: 2.8,
    netWeight: 2.6,
    color: "Yellow Gold",
    tags: ["chain", "versatile", "gold"],
    metalValue: 1100,
    stoneValue: 0,
  },
  {
    id: "8",
    name: "Pearl Drop Earrings",
    description:
      "White pearl drops with gold setting. These elegant pearl drop earrings feature lustrous white pearls suspended from 18k yellow gold wire, creating a graceful silhouette.",
    price: 950,
    image: "/pearl-drop-earrings.png",
    images: ["/pearl-drop-earrings.png"],
    category: "earrings",
    subcategory: "pearl",
    type: "drop",
    inStock: true,
    productCode: "ER-008-YG",
    designNumber: "D-3741",
    metalClarity: "18K Yellow Gold",
    shape: "Teardrop Pearl",
    size: "1.5 inches",
    purityKarat: "18K",
    grossWeightGram: 1.9,
    netWeight: 1.7,
    color: "White Pearl",
    tags: ["drops", "pearl", "elegant"],
    metalValue: 600,
    stoneValue: 300,
  },
  {
    id: "9",
    name: "Gold Bangle Bracelet",
    description:
      "Classic hinged gold bangle with diamond accents. This timeless bangle bracelet combines the luxury of gold with sparkling diamond accents, making it perfect for formal and casual occasions.",
    price: 2800,
    image: "/gold-bangle-bracelet.png",
    images: ["/gold-bangle-bracelet.png"],
    category: "bracelets",
    subcategory: "gold",
    type: "bangle",
    inStock: true,
    bestSeller: true,
    productCode: "BR-009-YG",
    designNumber: "D-6512",
    metalClarity: "18K Yellow Gold",
    shape: "Hinged Bangle",
    size: "6.5-7 inches",
    purityKarat: "18K",
    grossWeightGram: 7.1,
    netWeight: 6.8,
    color: "Yellow Gold",
    tags: ["bangle", "diamonds", "classic"],
    metalValue: 2000,
    stoneValue: 700,
  },
  {
    id: "10",
    name: "Sapphire Ring",
    description:
      "Deep blue sapphire with diamond halo. This stunning cocktail ring features a vibrant deep blue sapphire surrounded by a halo of diamonds, creating a striking and sophisticated look.",
    price: 4500,
    image: "/sapphire-diamond-ring.jpg",
    images: ["/sapphire-diamond-ring.jpg"],
    category: "rings",
    subcategory: "gemstone",
    type: "cocktail",
    inStock: true,
    productCode: "RG-010-WG",
    designNumber: "D-7325",
    metalClarity: "18K White Gold",
    shape: "Oval Sapphire",
    size: "6, 7, 8, 9",
    purityKarat: "18K",
    grossWeightGram: 5.8,
    netWeight: 5.4,
    color: "White Gold",
    tags: ["sapphire", "halo", "cocktail"],
    metalValue: 1500,
    stoneValue: 2800,
  },
  {
    id: "11",
    name: "Multi-Strand Pearl Necklace",
    description:
      "Luxurious 3-strand pearl necklace. This sophisticated piece features three strands of lustrous white pearls graduated in size, creating an elegant and refined appearance.",
    price: 3500,
    image: "/multi-strand-pearl-necklace.jpg",
    images: ["/multi-strand-pearl-necklace.jpg"],
    category: "necklaces",
    subcategory: "pearl",
    type: "statement",
    inStock: true,
    productCode: "NK-011-YG",
    designNumber: "D-8956",
    metalClarity: "14K Yellow Gold",
    shape: "Multi-Strand Pearl",
    size: "18 inches",
    purityKarat: "14K",
    grossWeightGram: 4.5,
    netWeight: 4.1,
    color: "White Pearl",
    tags: ["statement", "pearls", "luxury"],
    metalValue: 1800,
    stoneValue: 1500,
  },
  {
    id: "12",
    name: "Halo Diamond Ring",
    description:
      "1.5-carat center diamond with halo setting. This breathtaking ring features a 1.5-carat center diamond surrounded by a halo of smaller diamonds, creating maximum sparkle and sophistication.",
    price: 10000,
    image: "/halo-diamond-ring.jpg",
    images: ["/halo-diamond-ring.jpg"],
    category: "rings",
    subcategory: "diamond",
    type: "engagement",
    inStock: false,
    productCode: "RG-012-WG",
    designNumber: "D-9847",
    metalClarity: "18K White Gold",
    shape: "Round Brilliant with Halo",
    size: "5, 6, 7, 8",
    purityKarat: "18K",
    grossWeightGram: 6.8,
    netWeight: 6.3,
    color: "White Gold",
    tags: ["engagement", "halo", "luxury"],
    metalValue: 2000,
    stoneValue: 7800,
  },
]
